### ISSUE TITLE
Add edgeshark links to the automation panel

### ISSUE THREAD

**Issue by hellt** [srl-labs/sros-anysec-macsec-lab#39]
The new automation panel (#38) should have another tile that would allow to select the node and its interface for traffic sniffing via Edgeshark.

@mairp @tiago-amado what interfaces are useful to add as a sniffing point?
We can have multiple interfaces on a single node selected as well. For example sniff on PE incoming and outgoing interface in one wireshark window.

Let us know what ports would be desired to have for a quick wireshark access

**Comment by tiago-amado** [comment]
Usually PE1 if 1 and 2, sometimes also 3 to show MACSec encrypted packets also when ANYSec is disabled.
CE5 may also be interesting if the focus is MACsec, to show packets in clear from client and encrypted to network.

A nice feature for EdgeShark would be to allow multiple interfaces across multiple nodes, but don't think it would be easy to redirect multiple captures to the same Wireshark session.

**Comment by hellt** [comment]
added in #42 for PE1:eth1 and PE1:eth2
